<a href="https://colab.research.google.com/github/todor-petrov/PyTorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Math Operations

*   Add, Subtract, Multipy, Divide, Remainders, Exponends
*   Shorthand and Longhand
*   Reassignment







In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Subtraction
tensor_b - tensor_a

In [ ]:
# Sub function
torch.sub(tensor_b, tensor_a)

In [6]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:
# Multiply function
torch.mul(tensor_a, tensor_b)

In [7]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [8]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [9]:
# Remainder Modules
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [10]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [11]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [12]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [13]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [14]:
tensor_a

tensor([1, 2, 3, 4])

In [15]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
tensor_a

tensor([ 6,  8, 10, 12])