<a href="https://colab.research.google.com/github/todor-petrov/Pythorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

Lists

In [8]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

Nympy

In [9]:
np1 = np.random.rand(3, 4)
np1

array([[0.9994125 , 0.21721666, 0.83626529, 0.75673768],
       [0.0237854 , 0.28552479, 0.56322587, 0.49215376],
       [0.12132981, 0.98533712, 0.9651761 , 0.671072  ]])

In [10]:
np1.dtype

dtype('float64')

Tensor

In [17]:
tensor_2d = torch.randn(3, 4)
tensor_2d
tensor_2d.dtype

torch.float32

In [14]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9994, 0.2172, 0.8363, 0.7567],
        [0.0238, 0.2855, 0.5632, 0.4922],
        [0.1213, 0.9853, 0.9652, 0.6711]], dtype=torch.float64)